### ISSUE TITLE
Contributing/Getting Started guide

### ISSUE THREAD

**Issue by PanopticaRising** [pj1234678/MagickaFix#11]
Hi @pj1234678 , can you provide some direction on how one could get involved in debugging and implementing fixes for the DLLs?

I've done a little C#/DLL hacking in the past for simple servers, but never for games. I'd love to help debug and improve the game, particularly the heavy memory usage issue.

**Comment by pj1234678** [comment]
I will rewrite the README tonight once 1.5 drops in a few hours.

The best thing you can do is:
1. Help spread the fix on steam and other parts of the internet since many people are unaware (Please link them directly to the GitHub)
2. Play the game and stress it out (e.x. doing wacky unorthodox things with friends) and submit the crash logs.

As more of this happens the game tends to smooth out.

I must further iterate:
This is only a Quality of Life mod to make the game retain itself as time goes by there will be other things that we will eventually find. Different hardware treats the game differently.

**Comment by pj1234678** [comment]
The new version dropped.

I have updated the Readme to make it more friendly.
