### ISSUE TITLE
VAC Ban concern

### ISSUE THREAD

**Issue by fenjalien** [pj1234678/MagickaFix#18]
I'm looking in to using this but I'm concerned it may cause a VAC ban as according to this reddit post: https://www.reddit.com/r/magicka/comments/14yp9ym/release_magicka_fixes_for_multiplayer_and/ it disables the dlc check. Does this allow the use of unpurchased DLC? If so it doesn't feel right. I can't find anyone else talking about this. 

A detailed list of fixes on the repository here would also help.

**Comment by pj1234678** [comment]
Hello fenjalien,

1. This game does not utilize VAC. This information would typically be visible on Magicka's Steam store page.

2. We do not endorse the disabling of any licensing mechanisms.  We encourage all players to purchase the original game and support the developers, as stated in the readme.

Regarding the check you mentioned, I assume it's related to:

"Patched "CheckSteamDLCs" to do nothing disables the check for Steam DLCs via a broken TLS connection."

What this function actually does is remove the faulty TLS connection logic that causes crashes.

To clarify, this change does not grant players access to anything they haven't already purchased. It simply prevents the game from crashing due to a broken TLS connection.
